Repository Rebuild-Studio/Client, pull requests merged in 2023-10, with the labels that each got.

#127 fix: 슬라이더 너비 조정
  src/components/common/Slider.tsx
Labels: 🐞 Bug

#133 feat: 로고 및 meta 데이터 설정
  index.html
  public/MX_logo.svg
  public/vite.svg
Labels: ✨ Feature, 📃 Docs

#111 Feat/capture thumbnail
  src/components/MenuBar.tsx
  src/components/TopBar.tsx
  src/features/projectList/components/ProjectList.tsx
  src/store/projectStore.ts
  src/three_components/common/Grid.tsx
  src/three_components/common/Scene.tsx
  src/three_components/scene/RenderScene.tsx
  src/utils/thumbnail.ts
Labels: ✨ Feature

#137 Delete .github/workflows/telegrambot-ci.yml
  .github/workflows/telegrambot-ci.yml
Labels: ⚙ Setting

#143 Feat: Showing styled component classname on devtool
  package-lock.json
  package.json
  vite.config.ts
Labels: ⚙ Setting

#146 style: 패널 스크롤 가능하게 변경
  src/components/layout/Panel/Panel.tsx
  src/components/layout/Tools.tsx
Labels: 🐞 Bug, 🚨 High priority, 🎨 Style

#131 Feat/hierarchy context menu
  src/App.tsx
  src/components/layout/CanvasLeftPanel/CanvasLeftPanel.tsx
  src/features/hierarchy/components/HierarchyElement.tsx
  src/features/hierarchy/components/HierarchyPanel.tsx
  src/features/hierarchy/utils/clearMouseEventHierarchy.ts
  src/features/hierarchy/utils/onClickHierarchyEvent.ts
  src/features/hierarchy/utils/onContextMenuHierarchyEvent.ts
  src/store/canvasHistoryStore.ts
  src/store/contextMenuStore.ts
  src/store/primitiveStore.ts
  src/stories/layouts/canvasLeftPanel/HierarchyPanel.stories.ts
  src/three_components/common/Scene.tsx
  src/three_components/group/Group.tsx
  src/three_components/utils/copyObject.ts
  src/three_components/utils/executeContextMenu.ts
  src/three_components/utils/onClickSceneEvents.ts
  src/three_components/utils/onContextMenuSceneEvents.ts
Labels: ✨ Feature

#151 Feat/round to decimal places
  src/components/common/RightPanel/TransformInput.tsx
  src/utils/number/roundToDecimalPlaces.ts
Labels: ✨ Feature

#183 chore: mv/core 패키지 버전업
  package-lock.json
  package.json
Labels: 🐞 Bug
